---
abstract: 'This module is a subclass of Digest using the Crypt::PBKDF2 algorithm.'
author:
  - 'Amiri Barksdale <abarksdale@campusexplorer.com>'
build_requires:
  Scalar::Util: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200012, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Digest-PBKDF2
requires:
  Crypt::PBKDF2: 0.112020
  Digest::base: 0
  parent: 0
resources:
  repository: git://github.com/amiri/Digest-PBKDF2.git
version: 0.009
